version: 0.2

phases:
  install:
    runtime_versions:
      nodejs: 18
    commands:
    - npm i -g npm
    - npm i -g @nestjs/cli
    - npm i -g typescript
  pre_build:
    commands:
    - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
    - echo 'build completed'


artifacts:
  files: 
    '**/*'